aliuacademy_org/academy/web/urls.py
# -*- encoding: utf-8 -*-
from django.conf.urls import (
    patterns,
    url,
)

from .views import (
    AboutView,
    CourseTopicListView,
    DepartmentCourseListView,
    TopicDetailView,
    UniversityDepartmentListView,
    UniversityListView,
    UniversitiesView,
    VisionView,
    VideoViewListView,    
    AjaxCommandView,
    DownloadMediaView
)


urlpatterns = patterns(
    '',
    url(regex=r'^about/$',
        view=AboutView.as_view(),
        name='web.about'
        ),
    url(regex=r'^academy/department/(?P<pk>\d+)/$',
        view=DepartmentCourseListView.as_view(),
        name='web.department.course.list'
        ),
    url(regex=r'^academy/university/(?P<slug>[-\w\d]+)/$',
        view=UniversityDepartmentListView.as_view(),
        name='web.university.department.list'
        ),
    url(regex=r'^academy/course/(?P<pk>\d+)/$',
        view=CourseTopicListView.as_view(),
        name='web.course.topic.list'
        ),
    url(regex=r'^academy/university/$',
        view=UniversityListView.as_view(),
        name='web.university.list'
        ),
    url(regex=r'^academy/topic/(?P<pk>\d+)/$',
        view=TopicDetailView.as_view(),
        name='web.topic.detail'
        ),
    url(regex=r'^universities/$',
        view=UniversitiesView.as_view(),
        name='web.universities'
        ),
    url(regex=r'^userprofile/$',
        view=VideoViewListView.as_view(),
        name='web.userprofile'
        ),
    url(regex=r'^vision/$',
        view=VisionView.as_view(),
        name='web.vision'
        ),
    url(regex=r'^ajaxcall/(?P<cmd>.*)/(?P<pk>\d+)/$',
        view=AjaxCommandView,
        name='ajaxcall.command.topic'
        ),
    url(regex=r'^download/(?P<topic_id>.*)/$',
        view=DownloadMediaView,
        name='download.media'
        ),
)

aliuacademy_org/academy/web/models.py
# -*- encoding: utf-8 -*-
"""Database models for Aliu's Academy."""

import os

from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.utils.text import slugify

import reversion

from base.model_utils import (
    ftp_file_store,
    TimeStampedModel,
)

class FlaggedTimeStampedModel(TimeStampedModel):
    """
    An abstract base class model that provides additional shared flags for Videos DB
    """
    is_active = models.IntegerField(default=1)

    class Meta:
        abstract = True

        
class FlaggedTimeStampedManager(models.Manager):
    """
    An abstract base class model that provides additional shared flags for Videos DB
    """
    def deactivate_all(self):
        self.model.objects.all().update(is_active=0)

    class Meta:
        abstract = True

        
class ActiveFlagTimeStampedManager(models.Manager):
    """
    A class to only return active Unis, Departs, Courses or Topics
    """
    def get_queryset(self):
        return super(ActiveFlagTimeStampedManager, self).get_queryset().filter(is_active=1)    
          
   

        
class UniversityManager(FlaggedTimeStampedManager):

    def create_university(self, folder_name):
        university = self.model(
            slug=slugify(folder_name),
            name=folder_name,
            folder_name=folder_name,
        )        
        university.save()
        return university

    def update_university(self, university):
        try:
            uni_match = self.model.objects.get(folder_name=university)
            uni_match.is_active = 1  
            uni_match.save()
        except University.DoesNotExist:
            self.create_university(folder_name=university)

           
    
class University(FlaggedTimeStampedModel):

    """University e.g. MIT."""

    slug = models.SlugField(max_length=100)
    name = models.CharField(max_length=100)
    folder_name = models.CharField(max_length=100, unique=True)
    objects = UniversityManager()
    active_objects = ActiveFlagTimeStampedManager()

    class Meta:
        ordering = ('slug',)

reversion.register(University)


class DepartmentManager(FlaggedTimeStampedManager):
        
    def create_department(self, university, folder_name):
        department = self.model(
            university=university,
            name=folder_name,
            folder_name=folder_name,
        )
        department.save()
        return department

    def update_department(self, university, department):
        uni = University.objects.get(folder_name=university)
        try:
            dept_match = self.model.objects.get(
                university=uni,
                folder_name=department
            )
            dept_match.is_active = 1
            dept_match.save()
        except Department.DoesNotExist:
            self.create_department(
                university=uni,
                folder_name=department,
            )


        
class Department(FlaggedTimeStampedModel):

    """Department at the University."""

    name = models.CharField(max_length=100)
    folder_name = models.CharField(max_length=100)
    university = models.ForeignKey(University)
    objects = DepartmentManager()
    active_objects = ActiveFlagTimeStampedManager()

    class Meta:
        ordering = ('name',)
        verbose_name = 'Department'
        verbose_name_plural = 'Departments'
        unique_together = ('university', 'folder_name',)

reversion.register(Department)


class CourseManager(FlaggedTimeStampedManager):

    def create_course(self, department, order, folder_name):
        course = self.model(
            department=department,
            order=order,
            name=folder_name,
            folder_name=folder_name,
        )
        course.save()
        return course

    def update_course(self, university, department, order, course):
        univ = University.objects.get(folder_name=university)
        dept = Department.objects.get(university=univ, folder_name=department)
        try:
            crs_match = self.model.objects.get(
                department=dept,
                folder_name=course
            )
            crs_match.is_active = 1
            crs_match.save()
        except Course.DoesNotExist:
            self.create_course(
                department=dept,
                order=order,
                folder_name=course,
            )



class Course(FlaggedTimeStampedModel):

    """Course e.g. Introduction to Computer Science."""

    order = models.IntegerField()
    name = models.CharField(max_length=100)
    folder_name = models.CharField(max_length=100)
    department = models.ForeignKey(Department)
    objects = CourseManager()
    active_objects = ActiveFlagTimeStampedManager()

    class Meta:
        ordering = ('order',)
        verbose_name = 'Course'
        verbose_name_plural = 'Courses'
        unique_together = ('department', 'folder_name',)

reversion.register(Course)


class ActiveVideoManager(ActiveFlagTimeStampedManager):
    """
    A class to only return active Unis, Departs, Courses or Topics
    """
    def get_queryset(self):
        return super().get_queryset().filter(
            is_active=1,
            file_type=Topic.VIDEO
        )


class ActiveWareManager(ActiveFlagTimeStampedManager):
    """
    A class to only return active Unis, Departs, Courses or Topics
    """
    def get_queryset(self):
        return super().get_queryset().filter(
            is_active=1,
            file_type=Topic.WARE
        )


class TopicManager(FlaggedTimeStampedManager):

    def create_topic(self, course, order, file_path, file_type):
        name = os.path.basename(file_path)
        name, _ = os.path.splitext(name)
        topic = self.model(
            order=order,
            name=name,
            video=file_path,
            course=course,
        )
        topic.file_type=file_type
        topic.save()
        return topic

    def update_topic(self, university, department, course, order, path, topic, file_type):
        univ = University.objects.get(folder_name=university)
        dept = Department.objects.get(university=univ, folder_name=department)
        cour = Course.objects.get(department=dept, folder_name=course)
        try:
            tpc_match = self.model.objects.get(
                course=cour,
                video=path,
            )
            tpc_match.is_active = 1
            tpc_match.order = order
            tpc_match.save()
            return tpc_match
        except Topic.DoesNotExist:
            return self.create_topic(
                course=cour,
                order=order,
                file_path=path,
                file_type=file_type,
            )


class Topic(FlaggedTimeStampedModel):

    """File stores the Video for the Topic."""
    VIDEO = 1
    WARE = 2
    TOPIC_FILE_TYPES = (
        (VIDEO, 'Video'),
        (WARE, 'Ware'),
    )
    order = models.IntegerField()
    name = models.CharField(max_length=150)
    video = models.FileField(
        max_length=300,
        upload_to='video/%Y/%m/%d',
        storage=ftp_file_store,
    )
    course = models.ForeignKey(Course)
    file_type = models.IntegerField(choices=TOPIC_FILE_TYPES,default=VIDEO)
    objects = TopicManager()
    active_objects = ActiveVideoManager()
    active_ware = ActiveWareManager()

    class Meta:
        ordering = ('order', 'name')
        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'
        unique_together = ('course', 'video',)

    def __str__(self):
        return '{}'.format(self.name)

    def download_file_name(self):
        return os.path.basename(self.video.name)

    @property
    def get_next(self):
        topic = Topic.active_objects.filter(
            course=self.course,
            order__gt=self.order,
        ).order_by(
            'order'
        )
        if topic:
            return topic[0]
        return None

    @property
    def get_prev(self):
        topic = Topic.active_objects.filter(
            course=self.course,
            order__lt=self.order,
        ).order_by(
            '-order'
        )
        if topic:
            return topic[0]
        return None

reversion.register(Topic)


class VideoViewManager(FlaggedTimeStampedManager):


    def get_topic_viewcounts(self, topic):    
        return self.model.objects.filter(viewed_topic=topic).aggregate(views=Sum('viewed'),dls=Sum('downloaded'))
    
    def create_view(self, topic, user, vw, dl):
        vd_view = self.model(
            viewed_topic=topic,
            viewer=user,
            viewed=vw,
            downloaded=dl,
        )
        vd_view.save()
        return vd_view

    def add_view(self, topic, user, vw, dl):

        try:
            vd_view = self.model.objects.get(
                viewed_topic=topic,
                viewer=user,
            )
            vd_view.viewed += int(vw)
            vd_view.downloaded += int(dl)
            vd_view.save()
            return vd_view
            
        except VideoView.DoesNotExist:
           return self.create_view(
                topic=topic,
                user=user,
                vw=vw,
                dl=dl,
            )


    
class VideoView(TimeStampedModel):
    viewed = models.IntegerField(default=0)
    downloaded = models.IntegerField(default=0)
    viewer = models.ForeignKey(settings.AUTH_USER_MODEL)
    viewed_topic = models.ForeignKey(Topic)
    objects = VideoViewManager()


class TopicCommentManager(FlaggedTimeStampedManager):

    def add_comment(self, topic, user, cmt):
        new_tc = self.model(
            comment=cmt,
            commentator=user,
            comment_topic=topic
        )
        new_tc.save()
        return new_tc
    
class TopicComment(TimeStampedModel):
    comment = models.TextField(max_length=500)
    commentator = models.ForeignKey(settings.AUTH_USER_MODEL)
    comment_topic = models.ForeignKey(Topic)
    objects = TopicCommentManager()

aliuacademy_org/academy/web/templates/web/about.html
{% extends 'web/base.html' %}
{% load staticfiles %}

{% block content %}
<h1 class="content-head">
  Aliu Academy
</h1>
<p>
    ALIU ACADEMY is an initiative that aims to use technology to
    bring rich and world class educational opensource contents
    from some of the best institutions in the world to
    University communities in Africa such that students can
    access the resources in an offline environment at speeds
    comparable to high speed broadband in other parts of the
    world with high speed internet.
</p>
<p>
    Fast internet technologies have not reached most parts of
    the world and Africa is not an exception, in fact   <b> 65% of the
    world have no access to high speed internet connection </b>.
</p>
<p>But the world does not wait. Technology keeps pushing beyond to
    the limit and there is an exponential spread of knowledge in
    what has grown to be known as massive online open courses
    (MOOC) where some of the best schools in the world such as
    MIT, Harvard, Stanford, Yale, University of Califonia
    Berkeley, IIT india, etc offer educational resources for
    free mostly real life lecture videos. But to watch these
    videos and make any sense of them requires high speed
    internet which for now is not totally practicable across
    Africa. 
</p>
<h3>
    What should we do?
</h3>
<p> 
We can't fold our hands and wait
till high speed broadband comes before we tap into these
technologies and join the world in advancement of knowledge!
Hence the motivation to build a platform that will locally
distribute the contents of these resources such that
University communities can have access to these resources at
super fast speed through a WIFI based local area network.
Students can access materials on the server from their
mobile devices like Android, iPhone,iPad and laptops as well
as desktops at a speed that will make them feel they are
truly in the 21st century. 
</p>
<p>
<b>We hope to expand and collaborate more with stakeholders to spread knowledge for free and
light up the continent for present and future generations.</b>
</p>

{% endblock content %}


{% block sidemenu %}
<div style="padding:20px;font-size: 110%;color:#34495e;background-image:url({% static 'img/project/' %}nelson-mandela.png);  background-position: center; background-size: 100% ;background-repeat: no-repeat;">
    <p>
    <strong>
    "Education is the great engine of personal development. It is through education that the daughter of a persant can become a  doctor, that a son of a mineworker can become the head of the
      mine, that a child of farm workers can become the president of a great nation. It is what we make out of what we have, not what we are given, that separates one person from another." 
    </strong>   
    </p>
    <h2>Nelson Mandela</h2>  
</div>
{% endblock sidemenu %}

aliuacademy_org/academy/web/templates/web/base.html
{% extends 'project/base.html' %}

{% block heading %}
  aliuacademy.org
{% endblock heading %}

{% block footer %}
{% endblock footer %}

aliuacademy_org/academy/web/templates/web/base_sidebar.html
{% extends 'web/base.html' %}

{% block sidemenu %}
    <div class="pure-menu custom-side-menu">    
        <div class="pure-menu pure-menu-open" >
            <ul class="pure-menu-list">
            {% block sidemenuitems %}
            {% endblock sidemenuitems %}   
            </ul> 
        </div> 
    </div>
{% endblock sidemenu %}   

aliuacademy_org/academy/web/templates/web/course_list.html
{% extends 'web/base_sidebar.html' %}
{% load staticfiles %}

{% block sub_title %}
  Course
{% endblock sub_title %}

{% block sub_heading %}
  Course
{% endblock sub_heading %}


{% block content %}
<h1 class="content-head">{{ department.name }} Courses</h1>
<p>
Click to select a course.
</p>
{% endblock content %}


{% block sidemenuitems %}
    <li class="pure-menu-item"><a href="{% url 'web.university.list' %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> My Universities</a></li>
    <li class="pure-menu-item"><a href="{% url 'web.university.department.list' department.university.slug %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> {{ department.university.name }} University</a></li>
    <li class="pure-menu-heading">{{ department.name }} Department</li>
    <li><span class="pure-menu-link pure-menu-instruction">Select a Course</span></li>
    {% for course in course_list %} 
    <li class="pure-menu-item"><a href="{% url 'web.course.topic.list' course.pk %}" class="pure-menu-link">{{ course.name }}</a></li>
    {% endfor %}
    
{% endblock sidemenuitems %}

aliuacademy_org/academy/web/templates/web/department_list.html
{% extends 'web/base_sidebar.html' %}
{% load staticfiles %}

{% block sub_title %}
  Departments
{% endblock sub_title %}

{% block sub_heading %}
  Departments
{% endblock sub_heading %}


{% block content %}
<h1 class="content-head">Departments at {{ university.name }}</h1>
<p>
Click to select a department.
</p>
{% endblock content %}



{% block sidemenuitems %}
    <li class="pure-menu-item"><a href="{% url 'web.university.list' %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> My Universities</a></li>
    <li class="pure-menu-heading">{{ university.name }} University</li>
    <li><span class="pure-menu-link pure-menu-instruction">Select Department</span></li>
    {% for department in department_list %} 
    <li class="pure-menu-item"><a href="{% url 'web.department.course.list' department.pk %}" class="pure-menu-link">{{ department.name }}</a></li>
    {% endfor %}

{% endblock sidemenuitems %}

aliuacademy_org/academy/web/templates/web/settings.html
{% extends 'project/base.html' %}
{% load staticfiles %}

{% block sub_title %}
  Settings
{% endblock sub_title %}

{% block sub_heading %}
  Settings
{% endblock sub_heading %}

{% block content %}
  <div class="pure-g">
    <div class="pure-u-1">
      <h4>Settings</h4>
    </div>
  </div>
  <div class="pure-g">
    {% if user.is_staff %}
      <div class="pure-u-1 pure-u-md-1-4">
        <div class="l-box">
			<ul>
			<li><a href="{% url 'project.settings.rebuilddb' %}">Rebuild DB</a></li>
			</ul>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock content %}

aliuacademy_org/academy/web/templates/web/topic_detail.html
{% extends 'web/base_sidebar.html' %}
{% load staticfiles %}

{% block sub_title %}
  Topic
{% endblock sub_title %}

{% block sub_heading %}
  Topic
{% endblock sub_heading %}

{% block content %}

    <h1 class="content-head">{{ topic.name }}</h1>    

	<video controls>
        <source src="{{ topic.video.url }}" type="video/mp4">
        <source src="{{ topic.video.url }}" type="video/ogg">
        Your browser does not support the video tag.
    </video>

    <div style="margin-top:30px;width:100%;">
        <span class="counterbox" style="" title="View Count"><i class="fa fa-eye"></i> <span  id="vd_viewcount">{{vid_vw.views|default_if_none:0}}</span></span>
        <span class="counterbox" style="" title="Download Count"><i class="fa  fa-folder-o"></i> <span  id="vd_dlcount">{{vid_vw.dls|default_if_none:0}}</span></span>

        {% if topic.get_prev %}
          <a href="{% url 'web.topic.detail' topic.get_prev.pk %}" class="pure-button counterbox">
            Prev
          </a>
        {% endif %}
        {% if topic.get_next %}
          <a href="{% url 'web.topic.detail' topic.get_next.pk %}" class="pure-button counterbox">
            Next
          </a>
        {% endif %}

        <a id="vd_download" href="{% url 'download.media' topic.pk %}" download="{{ topic.download_file_name }}" class="pure-button" style="float:right;">
          <i class="fa fa-download"></i>
          Download
        </a>
        <!--
        <a id="vd_download2" href="{{ topic.video.url }}" download="{{ topic.download_file_name }}" class="pure-button" style="float:right;">
          <i class="fa fa-download"></i>
          HREF
        </a>
        -->
    </div>

    <div id="comment_list" style="margin-top:30px;width:100%;">
    <div class="pure-menu-heading">Comments</div>
    {% for cmt in comment_list %}
        <div class="comment">
            <label>{{ cmt.created|date:"SHORT_DATETIME_FORMAT" }} <i>posted by</i> <b> {{ cmt.commentator.username }}</b></label>
            <p>{{ cmt.comment }}</p>
        </div>
    {% endfor %}
    </div>

    <div style="margin-top:30px;width:100%;">
        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="pure-button" style="float:right;" value="Add Comment" />  
        </form>
    </div> 
    
    
    <script>
    
        // listen for the video to end - ajax call updates view count in db and label
        var v = document.getElementsByTagName("video")[0];
        v.addEventListener("ended", function() { 
                var xmlhttp = get_xmlhttp();              
                xmlhttp.onreadystatechange=function()
                  {
                  if (xmlhttp.readyState==4 && xmlhttp.status==200)
                    {
                    // ajax view function adds the view count to the db, then returns the total number of views including this one
                    document.getElementById("vd_viewcount").innerHTML=xmlhttp.responseText;
                    }
                }
                xmlhttp.open("GET","/web/ajaxcall/viewcount/{{topic.id}}/",true);
                xmlhttp.send();
        }, true);
        
        // listen for the download button being clicked - ajax call updates dl count in db and label
        var d = document.getElementById("vd_download");
        d.addEventListener("click", function() { 
                var xmlhttp = get_xmlhttp();              
                xmlhttp.onreadystatechange=function()
                  {
                  if (xmlhttp.readyState==4 && xmlhttp.status==200)
                    {
                    // ajax view function adds the dl count to the db, then returns the total number of views including this one
                    document.getElementById("vd_dlcount").innerHTML=xmlhttp.responseText;
                    }
                }
                xmlhttp.open("GET","/web/ajaxcall/dlcount/{{topic.id}}/",true);
                xmlhttp.send();
        }, true);
        
        function get_xmlhttp() {
            if (window.XMLHttpRequest)
                {// code for IE7+, Firefox, Chrome, Opera, Safari
                return new XMLHttpRequest();
                }
            else
                {// code for IE6, IE5
                return new ActiveXObject("Microsoft.XMLHTTP");
                };
        };
    </script>
    
{% endblock content %}


{% block sidemenuitems %}

    <li class="pure-menu-item"><a href="{% url 'web.university.list' %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> My Universities</a></li>
    <li class="pure-menu-item"><a href="{% url 'web.university.department.list' topic.course.department.university.slug %}"  class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> {{ topic.course.department.university.name }} University</a></li>
    <li class="pure-menu-item"><a href="{% url 'web.department.course.list' topic.course.department.pk %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> {{ topic.course.department.name }}</a></li>
    <li class="pure-menu-item"><a href="{% url 'web.course.topic.list' topic.course.pk %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> {{ topic.course.name }}</a></li>

    <li class="pure-menu-heading">{{ topic.name }}<li>
    
    {% for tpc in topic_list %}
	{% if forloop.first %}<li><span class="pure-menu-link pure-menu-instruction">Select another Topic</span></li>{% endif %}
		{% if tpc != topic %}
		<li class="pure-menu-item"><a href="{% url 'web.topic.detail' tpc.pk %}" class="pure-menu-link">{{ tpc.name }}</a></li>
		{% else %}
		<li><span class="pure-menu-link ">{{ tpc.name }}</span></li>
		{% endif %}
    {% endfor %}

    {% for tpc in ware_list %}
    {% if forloop.first %}
    <li class="pure-menu-heading">Course Ware<li>
    <li><span class="pure-menu-link pure-menu-instruction">Click to download</span></li>
    {% endif %}
    <li class="pure-menu-item"><a href="{% url 'download.media' tpc.pk %}" download="{{ topic.download_file_name }}" class="pure-menu-link">{{ tpc.name }}</a></li>
    {% endfor %}

{% endblock sidemenuitems %}



 
    

aliuacademy_org/academy/web/templates/web/topic_list.html
{% extends 'web/base_sidebar.html' %}
{% load staticfiles %}

{% block sub_title %}
  Topics
{% endblock sub_title %}

{% block sub_heading %}
  Topics
{% endblock sub_heading %}

{% block content %}
<h1 class="content-head">{{ course.name }} Topics</h1>
<p>
Click to select a topic.
</p>
{% endblock content %}


{% block sidemenuitems %}

    <li class="pure-menu-item"><a href="{% url 'web.university.list' %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> My Universities</a></li>
    <li class="pure-menu-item"><a href="{% url 'web.university.department.list' course.department.university.slug %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" /> {{ course.department.university.name }} University</a></li>
    <li class="pure-menu-item"><a href="{% url 'web.department.course.list' course.department.pk %}" class="pure-menu-link"><img src="{% static 'img/project/' %}arrow-back-left.png" />{{ course.department.name }} Department</a></li>

    <li class="pure-menu-heading">{{ course.name }}<li>

    <li><span class="pure-menu-link pure-menu-instruction">Select a Topic</span></li>

    {% for topic in topic_list %}
    <li class="pure-menu-item"><a href="{% url 'web.topic.detail' topic.pk %}" class="pure-menu-link">{{ topic.name }}</a></li>
    {% endfor %}
        
        
        
    
    {% for tpc in ware_list %}
    {% if forloop.first %}
    <li class="pure-menu-heading">Course Ware<li>
    <li><span class="pure-menu-link pure-menu-instruction">Click to download</span></li>
    {% endif %}
    <li class="pure-menu-item"><a href="{% url 'download.media' tpc.pk %}" download="{{ tpc.download_file_name }}" class="pure-menu-link">{{ tpc.name }}</a></li>
    {% endfor %}


{% endblock sidemenuitems %}

aliuacademy_org/academy/web/templates/web/universities.html
{% extends 'web/base.html' %}


{% block content %}
<h1 class="content-head">
  About the Universities
</h1>
  <p>
    Our database of educational videos are from some of the very
    best institutions in the world offering massive online open
    courses. The universities include MIT, Harvard, University of
    Califonia Berkeley, IIT India, Yale, Stanford. Most of these
    universities have pioneered some of the greatest inventions on
    earth and have trained some of the richest, most powerful and
    most influential people on earth hence a real class lecture
    coming from such schools for FREE is a gift that cannot be
    priced. We hope to continue to expand this database and bring
    world class educational materials to the end of the earth
  </p>
{% endblock content %}

aliuacademy_org/academy/web/templates/web/university_list.html
{% extends 'web/base_sidebar.html' %}
{% load staticfiles %}
{% block sub_title %}
  Universities
{% endblock sub_title %}

{% block sub_heading %}
  Universities
{% endblock sub_heading %}


{% block content %}
<h1 class="content-head">Select a University</h1>
<p>
Any universities associated with your account are shown in the right hand navigation box. Click to select a university.
</p>
{% endblock content %}


{% block sidemenuitems %}    
    <li class="pure-menu-heading">My Universities</li>
    <li><span class="pure-menu-link pure-menu-instruction">Select University</span></li>
    {% for university in university_list %}
    <li class="pure-menu-item"><a href="{% url 'web.university.department.list' university.slug %}" class="pure-menu-link">{{ university.name }}</a></li>
    {% endfor %}  
    
{% endblock sidemenuitems %}

aliuacademy_org/academy/web/templates/web/videoview_list.html
{% extends 'web/base_sidebar.html' %}
{% load staticfiles %}

{% block sub_title %}
  User Profile
{% endblock sub_title %}

{% block sub_heading %}
  Topics
{% endblock sub_heading %}

{% block content %}
<h1 class="content-head">Viewed Topics</h1>
<p>
Click to select a recently viewed or downloaded topic.
</p>
{% endblock content %}

   
{% block sidemenuitems %}

    <li><span class="pure-menu-heading">Topics Viewed</span></li>

    {% for vw in view_list %}
    <li class="pure-menu-item"><a href="{% url 'web.topic.detail' vw.viewed_topic.id %}" class="pure-menu-link">{{ vw.viewed_topic.name }} <i class="fa fa-eye"></i> {{ vw.viewed }}</a></li>
    {% endfor %}

    <li><span class="pure-menu-heading">Topics Downloaded</span></li>

    {% for dl in dl_list %}
    <li class="pure-menu-item"><a href="{% url 'web.topic.detail' dl.viewed_topic.id %}" class="pure-menu-link">{{ dl.viewed_topic.name }} <i class="fa fa-folder-o"></i> {{ dl.downloaded }}</a></li>
    {% endfor %}
        
{% endblock sidemenuitems %}

aliuacademy_org/academy/web/templates/web/vision.html
{% extends 'web/base.html' %}


{% block heading_extra %}

{% endblock heading_extra %}

{% block content %}

<h1 class="content-head">
  Our vision
</h1>
<p>

    Our vision at ALIU ACADEMY is to use technology to spread
    education across Africa and other parts of the world because
    we believe in the words of Nelson Mandela: 
    
    <blockquote> 
    "Education is the most powerful weapon which you can use to change the world.
    It is the great engine of personal development. It is through
    education that the daughter of a peasant can become a doctor,
    that a son of a mineworker can become the head of the mine,
    that a child of farm workers can become the president of a
    great nation."
    </blockquote>

</p>
{% endblock content %}